version: "3.3"


services:
  traefik:
    container_name: "traefik"
    image: traefik
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    networks:
      - rede-externa
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.localhost`)
      - traefik.http.routers.api.service=api@internal


  postgres:
    container_name: "postgres"
    image: postgres:alpine
    environment:
      POSTGRES_DB: maratona
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      TZ: GMT-4
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - rede-interna

  flyway:
    container_name: "flyway"
    image: dhoer/flyway:alpine
    command: -url=jdbc:postgresql://postgres:5432/maratona -schemas=public -user=postgres -password=admin migrate
    volumes:
      - ./migrations/migrations:/flyway/sql
    depends_on:
      - postgres
    networks:
      - rede-interna

  seeder:
    container_name: "seeder"
    build:
      context: ./migrations
    depends_on:
      - flyway
    networks:
      - rede-interna

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      POSTGRES_USER: postgres
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - rede-interna
      - rede-externa
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pg.localhost`)
      - traefik.http.routers.pgadmin.entrypoints=web

  zookeeper:
    container_name: "zookeeper"
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"


  kafka:
    container_name: "kafha"
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"

  producer:
    container_name: "producer"
    build:
      context: ./producer
    depends_on:
      - postgres
    networks:
      - rede-externa
    labels:
      - traefik.enable=true
      - traefik.http.routers.producer.rule=Host(`localhost`)
      - traefik.http.routers.producer.entrypoints=web


networks:
  rede-interna:
  rede-externa:
